/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MajorsEnviromentalSciencesRouteImport } from './routes/majors/enviromental-sciences'
import { Route as MajorsComputerScienceRouteImport } from './routes/majors/computer-science'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorsEnviromentalSciencesRoute =
  MajorsEnviromentalSciencesRouteImport.update({
    id: '/majors/enviromental-sciences',
    path: '/majors/enviromental-sciences',
    getParentRoute: () => rootRouteImport,
  } as any)
const MajorsComputerScienceRoute = MajorsComputerScienceRouteImport.update({
  id: '/majors/computer-science',
  path: '/majors/computer-science',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/majors/computer-science': typeof MajorsComputerScienceRoute
  '/majors/enviromental-sciences': typeof MajorsEnviromentalSciencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/majors/computer-science': typeof MajorsComputerScienceRoute
  '/majors/enviromental-sciences': typeof MajorsEnviromentalSciencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/majors/computer-science': typeof MajorsComputerScienceRoute
  '/majors/enviromental-sciences': typeof MajorsEnviromentalSciencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/majors/computer-science' | '/majors/enviromental-sciences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/majors/computer-science' | '/majors/enviromental-sciences'
  id:
    | '__root__'
    | '/'
    | '/majors/computer-science'
    | '/majors/enviromental-sciences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MajorsComputerScienceRoute: typeof MajorsComputerScienceRoute
  MajorsEnviromentalSciencesRoute: typeof MajorsEnviromentalSciencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majors/enviromental-sciences': {
      id: '/majors/enviromental-sciences'
      path: '/majors/enviromental-sciences'
      fullPath: '/majors/enviromental-sciences'
      preLoaderRoute: typeof MajorsEnviromentalSciencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majors/computer-science': {
      id: '/majors/computer-science'
      path: '/majors/computer-science'
      fullPath: '/majors/computer-science'
      preLoaderRoute: typeof MajorsComputerScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MajorsComputerScienceRoute: MajorsComputerScienceRoute,
  MajorsEnviromentalSciencesRoute: MajorsEnviromentalSciencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
