/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MajorsIndexRouteImport } from './routes/majors/index'
import { Route as MajorsMajorRouteImport } from './routes/majors/$major'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorsIndexRoute = MajorsIndexRouteImport.update({
  id: '/majors/',
  path: '/majors/',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorsMajorRoute = MajorsMajorRouteImport.update({
  id: '/majors/$major',
  path: '/majors/$major',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/majors/$major': typeof MajorsMajorRoute
  '/majors': typeof MajorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/majors/$major': typeof MajorsMajorRoute
  '/majors': typeof MajorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/majors/$major': typeof MajorsMajorRoute
  '/majors/': typeof MajorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/majors/$major' | '/majors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/majors/$major' | '/majors'
  id: '__root__' | '/' | '/about' | '/majors/$major' | '/majors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MajorsMajorRoute: typeof MajorsMajorRoute
  MajorsIndexRoute: typeof MajorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majors/': {
      id: '/majors/'
      path: '/majors'
      fullPath: '/majors'
      preLoaderRoute: typeof MajorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majors/$major': {
      id: '/majors/$major'
      path: '/majors/$major'
      fullPath: '/majors/$major'
      preLoaderRoute: typeof MajorsMajorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MajorsMajorRoute: MajorsMajorRoute,
  MajorsIndexRoute: MajorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
